title: Shaoliang Nie blog
url: "https://snie2012.github.io"
github_username: snie2012

markdown: kramdown
permalink: /blog/:year/:month/:day/:title

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 15